### PR TITLE
FeaturePopups for cluster strategy and WFS.v1_1_0 protocol

### PR DESCRIPTION
**Pull request by jorix**
Hello,

My issue is that when I click a dot from kpiBlackDotsLayer the popup isn't visible on the map. How can I resolve this problem?

my layer is defined like this:

```
this.kpiBlackDotsLayer = new OpenLayers.Layer.Vector("older releases", {
            visibility : false,
            strategies: [new OpenLayers.Strategy.BBOX(), new OpenLayers.Strategy.Cluster(), me.refreshStrategy2],
            extractAttributes: true,
            protocol: new OpenLayers.Protocol.WFS.v1_1_0({
                url:  'rest/map/wfs/blackdots/' + me.itemId,
                featureNS: link,
                featureType: 'points',
                featurePrefix : 'fr',
                srsName: 'EPSG:4326',
                geometryName: 'point',
                extractAttributes: true
            }),
            styleMap: new OpenLayers.StyleMap({"default": styleDefBlackDots})
        });
```

and the feature popup is like this:

```
var fpControl = new OpenLayers.Control.FeaturePopups();
        fpControl.addLayer(this.kpiBlackDotsLayer, {
            templates: {
                hover: "<h2>${.systemType}      </h2>Reporting: ${.reporting} <br>Pacients: ${.patients}<,
                single: "<h2>${.systemType} </h2>Reporting:${.reporting} <br>",
                item: "${showPopup()}"
                }
            });
```

Thank you!
   Elena

### CODE REVIEW

**Comment by dumbo611** [comment]
The answer of WFS is ok, because the list of information (that happends at the mouse over event) is loading with the correct data, but when I click on the feature the popup with the detailed information doesn't appear (this is my issue). I've tried without me.refreshStrategy2 and replaced item with what you said but still no change.

**Comment by jorix** [comment]
@dumbo611 thanks for the tests. Dismissed this, I looked for other reasons:

I think I've reproduced the problem on click: the popups are not displayed if the layer is not visible when added to the control.

I'll work on this...

**Comment by jorix** [comment]
@dumbo611 

Could you try this patch #2?, or just change the line [L1739](https://github.com/jorix/OL-FeaturePopups/pull/2/files#L0L1739) -- to remove `this.layer.getVisibility() &&`--
(other changes do not affect in this case)

**Comment by dumbo611** [comment]
After I've removed this.layer.getVisibility() && from line 1739 it's working.
Thank you!

**Pull request merged**
